kepler471/moonshot

- Moonshot/main_game.gd
- Moonshot/room_templates/BaseRoom.gd
> Fix for exit signal doubling.

- Moonshot/Combat/bullet.gd
- Moonshot/StateMachine/StateMachine.gd
- Moonshot/player/States/air.gd
- Moonshot/player/States/move.gd
- Moonshot/player/States/wall.gd
- Moonshot/player/player.gd
- Moonshot/player/player.tscn
- Moonshot/project.godot
WALL JUMPING BABYYYYYYYYYYYYYYYYY #38 
Have a feel of this player.
Intern will stick to a wall on collision. Direct Intern away from a wall to drop, and press jump to..... jump.
Please let me know of any errors, and any suggestions for how it feels.
DANKE
> Player  tweak mechanics

- Moonshot/project.godot
Made the camera size 1024x576  (from 1024x600) to fit 16:9 screen ratio.
> Camera size adjustment

- Moonshot/room_CANVAS.tscn
Duplicate the scene and go to town. 
Don't change cavas node names.
Best to delete unused doors.
> room_CANVAS for new rooms

- Moonshot/player/player.gd
TIN
... also small cleanup to player.gd, moved some logic out of _physics_process
> Make player face mouse in every state

- Moonshot/project.godot
I think this will have a conflict every pull due to the way the file autogen deals with default values.
> Remove a line which godot autodeletes.

- Moonshot/procedural_map_generation/draw_map.gd
As it says on the tin. Simples.
> Fog of war added to minimap

- Moonshot/player/player.gd
- Moonshot/player/player.tscn
Tiny change, cursor given a fixed position, and I have captured the mouse within the game window.
In DEBUG the actual ouse position will show, but the intention is that the mouse is hidden in game.
> (enhancement) cursor given fixed position from player

- Moonshot/player/player.gd
I guess this was missed, but animation name was not being initialised. Was this running for you @Jamesbarford ? This new change works for me.
> (fix #130) fixed error, animation_name null

- Moonshot/player/player.tscn
Placeholder animation, although it doesn't look terrible
> (fix #139) update player with stagger animation

- Moonshot/player/player.gd
- Moonshot/project.godot
Press `M` to capture the mouse. Also capture for non debug build.
> (fix) mouse capture only when asked for

- Moonshot/baddies/Attributes.gd
- Moonshot/procedural_map_generation/DifficultyController.gd
- Moonshot/procedural_map_generation/Room.gd
Each baddie attribute will need setting with a min and max attribute for the first level, and a factor that cotrols its scaling with level number
> Difficulty controller now in charge of level difficulty

- Moonshot/player/LedgeWallDetector.gd
- Moonshot/player/States/wall.gd
Rays are now directed by player velocity rather then player input. 
Fixes some little issues with wall jumping. 
May need further adjustment for _perfection._
> Fix: Ray-detection-update

- Moonshot/baddies/BaddieLaser/BaddieLaserPointer.gd
- Moonshot/main_game.gd
- Moonshot/room_templates/BaseRoom.gd
- Moonshot/room_templates/next_level_button.gd
- Moonshot/room_templates/next_level_button.tscn
- Moonshot/room_templates/room_scenes/room_base.tscn
- Moonshot/room_templates/room_scenes/room_test_down_entrance.tscn
- Moonshot/room_templates/room_scenes/room_test_left_entrance.tscn
- Moonshot/room_templates/room_scenes/room_test_right_entrance.tscn
- Moonshot/room_templates/room_scenes/room_test_up_entrance.tscn
Button can now be used by pressing enter whilst in the white area. Initial functionality, sprite and level_up processto be expanded on.
Next step is to decide how we are going to level up (falling, going through a cave exit) & if the boss room is locked upon entry
> Level up button

- Moonshot/SplashScreen.tscn
- Moonshot/items_objects/weapon_pickups/Big.gd
- Moonshot/items_objects/weapon_pickups/Big.tscn
- Moonshot/items_objects/weapon_pickups/Broken.gd
- Moonshot/items_objects/weapon_pickups/Broken.tscn
- Moonshot/items_objects/weapon_pickups/LaserBlaster.gd
- Moonshot/items_objects/weapon_pickups/LaserBlaster.tscn
- Moonshot/items_objects/weapon_pickups/MachineGun.gd
- Moonshot/items_objects/weapon_pickups/MachineGun.tscn
- Moonshot/items_objects/weapon_pickups/Shotgun.gd
- Moonshot/items_objects/weapon_pickups/Shotgun.tscn
- Moonshot/items_objects/weapon_pickups/TwinShot.gd
- Moonshot/items_objects/weapon_pickups/TwinShot.tscn
- Moonshot/player/player.gd
Items now change the players active weapon, sprites are missing though
> Weapon pickups now working

- story.txt
Ready to display line by line on the screen during the intro
> Initial story text

- Moonshot/Combat/bullet.gd
They now start from a random frame and rotation for the explosion. This makes it look alright on the machine chn and prevents an animation illusion (that the bullets aren't moving) with high firerate
> Changed the bullet animations 

- Moonshot/baddies/BaddieLaser/Blob.tscn
- Moonshot/baddies/characters/GhostyBoi.gd
- Moonshot/baddies/characters/GhostyBoi.tscn
Ghosty a bit stronger now, wider hitbox to drop blobs, higher blob drop rate
Ghosty now collides with Baddies, so they no longer overlap each other when hovering above the Intern
> (fix) Ghosty self collision and buff

- Moonshot/Combat/bullet.gd
…on for the explosion. This makes it look alright on the machine chn and prevents an animation illusion with high firerate
> add will's changes into dev

- Moonshot/HUD.gd
- Moonshot/main_game.gd
Not perfect but certaily neater.
Originally when I wrote the code I couldn't get the signalling to work, but in an ideal world, heath changes and firerate changes should be communicated to theHUD by signalling notinthe process part of the script. 
I could make it work now with a bit of time but I think this is a nice to have as it currently works.
> Have moved HUD code into a seperate script

- Moonshot/player/States/dodge.gd
- Moonshot/player/player.gd
> (fix) get direction input to find dodge direction

- Moonshot/HUD.gd
- Moonshot/main_game.gd
- Moonshot/main_game.tscn
- Moonshot/procedural_map_generation/draw_map.gd
Minimap now doesn't grow beyond its box, have also set the minimap to be centred so you can always see where you are
> Minimap boundaries

- Moonshot/procedural_map_generation/Room.gd
- Moonshot/procedural_map_generation/floor_generator.gd
Each room has a type and is stored in the relevant folder so that the floor generator algorithm can find it.
> Room types

- Moonshot/Autoload/Utils.gd
- Moonshot/default_bus_layout.tres
- Moonshot/player/PlayerArsenal.gd
- Moonshot/player/player.gd
Fix for laser blaster becoming mute on player spawning.
> Fix: Weapon muting

- Moonshot/Combat/bullet.gd
- Moonshot/baddies/BaddieLaser/Blob.gd
- Moonshot/items_objects/item_pickups/FirerateDropUnlock.gd
- Moonshot/items_objects/item_pickups/FireratePickup.gd
- Moonshot/room_templates/BaseRoom.gd
> fixes: firerate performance, empty array for baddies and animation on node

- Moonshot/Animations/Fade.gd
- Moonshot/baddies/Attributes.gd
- Moonshot/baddies/characters/BearDroppyBoi.gd
zero (okay, I'll be realistic maybe one) error on death  / when fading out / fading in / oscillating
> fix: fade out yeilding after leaving tree

- Moonshot/main_game.gd
> add delay timer

- Moonshot/Combat/Stats.gd
> (balancing) buff player HP

- Moonshot/Combat/Stats.gd
- Moonshot/HUD.gd
- Moonshot/baddies/Attributes.gd
- Moonshot/baddies/characters/BearBoi.gd
- Moonshot/baddies/characters/BearCeilingBoi.gd
- Moonshot/baddies/characters/BearDroppyBoi.gd
- Moonshot/baddies/characters/FlyBoi.gd
- Moonshot/baddies/characters/GhostyBoi.gd
- Moonshot/baddies/characters/MotherHen.gd
- Moonshot/baddies/characters/TankyBoi.gd
- Moonshot/baddies/characters/WallBoi.gd
- Moonshot/items_objects/item_pickups/HealthPickup.tscn
- Moonshot/main_game.gd
- Moonshot/player/LedgeWallDetector.gd
- Moonshot/player/PlayerArsenal.gd
- Moonshot/player/PlayerAudio.gd
- Moonshot/player/States/ledge.gd
- Moonshot/procedural_map_generation/DifficultyController.gd
- Moonshot/procedural_map_generation/draw_map.gd
- Moonshot/procedural_map_generation/level_gen.gd
- Moonshot/project.godot
- Moonshot/room_templates/BaseRoom.gd
- Moonshot/room_templates/next_level_button.gd
- Moonshot/splash_screen.gd
Lots of unfatal error fixes to clean the debugger. 
Broken up the commits, worth everyone looking at files they're familiar with just to check if I haven't ruined your best laid plans.
> Fix: Big Debug Error cleanup.

- Moonshot/baddies/characters/MotherHen.gd
- Moonshot/baddies/characters/MotherHen.tscn
- Moonshot/main_game.gd
- Moonshot/player/player.gd
- Moonshot/player/player.tscn
- For player death
- For spawner death
> (enhancement) Add slowmo effects

- Moonshot/Menu/StoryText.gd
Character names and text for that line are dictionary keys
> Story .gd file for easy access

- Moonshot/procedural_map_generation/draw_map.gd
- Moonshot/procedural_map_generation/floor_generator.gd
Minimap now displays connections next to the rooms that you visit
Boss room now spawns a minimum distance of 2 from the spawn room
> Minimap update and boss room distance

- Moonshot/player/player.gd
> move input to _physics_process as there were sync problems
